/**
 * 🔧 AI PROVIDER ACTION TYPES
 * 
 * Action types for managing AI provider configurations
 */

// FETCH AI PROVIDERS
export const FETCH_AI_PROVIDERS_REQUEST = 'aiProviders/FETCH_AI_PROVIDERS_REQUEST';
export const FETCH_AI_PROVIDERS_SUCCESS = 'aiProviders/FETCH_AI_PROVIDERS_SUCCESS';
export const FETCH_AI_PROVIDERS_FAILURE = 'aiProviders/FETCH_AI_PROVIDERS_FAILURE';

// CREATE AI PROVIDER
export const CREATE_AI_PROVIDER_REQUEST = 'aiProviders/CREATE_AI_PROVIDER_REQUEST';
export const CREATE_AI_PROVIDER_SUCCESS = 'aiProviders/CREATE_AI_PROVIDER_SUCCESS';
export const CREATE_AI_PROVIDER_FAILURE = 'aiProviders/CREATE_AI_PROVIDER_FAILURE';

// UPDATE AI PROVIDER
export const UPDATE_AI_PROVIDER_REQUEST = 'aiProviders/UPDATE_AI_PROVIDER_REQUEST';
export const UPDATE_AI_PROVIDER_SUCCESS = 'aiProviders/UPDATE_AI_PROVIDER_SUCCESS';
export const UPDATE_AI_PROVIDER_FAILURE = 'aiProviders/UPDATE_AI_PROVIDER_FAILURE';

// DELETE AI PROVIDER
export const DELETE_AI_PROVIDER_REQUEST = 'aiProviders/DELETE_AI_PROVIDER_REQUEST';
export const DELETE_AI_PROVIDER_SUCCESS = 'aiProviders/DELETE_AI_PROVIDER_SUCCESS';
export const DELETE_AI_PROVIDER_FAILURE = 'aiProviders/DELETE_AI_PROVIDER_FAILURE';

// SET ACTIVE PROVIDER
export const SET_ACTIVE_PROVIDER = 'aiProviders/SET_ACTIVE_PROVIDER';

// ERROR HANDLING
export const CLEAR_AI_PROVIDERS_ERROR = 'aiProviders/CLEAR_AI_PROVIDERS_ERROR';
