/**
 * 🏷️ MCP SERVERS ACTION TYPES
 * 
 * Enterprise pattern: Define all action types as constants
 */

// 📖 FETCH MCP SERVERS
export const FETCH_MCP_SERVERS_REQUEST = 'mcpServers/FETCH_MCP_SERVERS_REQUEST';
export const FETCH_MCP_SERVERS_SUCCESS = 'mcpServers/FETCH_MCP_SERVERS_SUCCESS';
export const FETCH_MCP_SERVERS_FAILURE = 'mcpServers/FETCH_MCP_SERVERS_FAILURE';

// ✨ CREATE MCP SERVER
export const CREATE_MCP_SERVER_REQUEST = 'mcpServers/CREATE_MCP_SERVER_REQUEST';
export const CREATE_MCP_SERVER_SUCCESS = 'mcpServers/CREATE_MCP_SERVER_SUCCESS';
export const CREATE_MCP_SERVER_FAILURE = 'mcpServers/CREATE_MCP_SERVER_FAILURE';

// ✏️ UPDATE MCP SERVER
export const UPDATE_MCP_SERVER_REQUEST = 'mcpServers/UPDATE_MCP_SERVER_REQUEST';
export const UPDATE_MCP_SERVER_SUCCESS = 'mcpServers/UPDATE_MCP_SERVER_SUCCESS';
export const UPDATE_MCP_SERVER_FAILURE = 'mcpServers/UPDATE_MCP_SERVER_FAILURE';

// 🗑️ DELETE MCP SERVER
export const DELETE_MCP_SERVER_REQUEST = 'mcpServers/DELETE_MCP_SERVER_REQUEST';
export const DELETE_MCP_SERVER_SUCCESS = 'mcpServers/DELETE_MCP_SERVER_SUCCESS';
export const DELETE_MCP_SERVER_FAILURE = 'mcpServers/DELETE_MCP_SERVER_FAILURE';

// 📡 SERVER STATUS
export const SET_SERVER_STATUS = 'mcpServers/SET_SERVER_STATUS';
export const TOGGLE_SERVER_ENABLED = 'mcpServers/TOGGLE_SERVER_ENABLED';
export const SET_SERVER_TOOLS = 'mcpServers/SET_SERVER_TOOLS';
export const REFRESH_AVAILABLE_TOOLS = 'mcpServers/REFRESH_AVAILABLE_TOOLS';

// ❌ ERROR HANDLING
export const CLEAR_MCP_ERROR = 'mcpServers/CLEAR_MCP_ERROR';
